programs:
  api:
    cmd: python3 api_server.py
    # autorestart: true
    numprocs: 2
    exitcodes: [0, 2]
    # startretries: 2
    starttime: 3
    autostart: false
    env:
      HOST: localhost
      PORT: '8089'
    workingdir: ../../workdir
    stdout: ../../logs/api.stdout
    stderr: ../../logs/api.stderr

    umask: 077

  worker:
    cmd: python3 worker.py
    # numprocs: 1
    umask: 022
    workingdir: ../../workdir
    autostart: true
    autorestart: unexpected
    exitcodes: 1
    startretries: 2
    starttime: 3
    stopsignal: INT
    stoptime: 1
    stdout: ../../logs/worker.stdout
    stderr: ../../logs/worker.stderr
    # env:
    #   STARTED_BY: taskmaster
    #   ANSWER: 42

  ls:
    cmd: /bin/ls -la
    numprocs: 1
    umask: 022
    workingdir: ../../workdir
    autostart: false
    autorestart: never

    stdout: ../../logs/ls.stdout
    stderr: ../../logs/ls.stderr
    
  attach:
    cmd: python3 attach.py
    numprocs: 1
    umask: 022
    workingdir: ../../workdir
    autostart: false
    autorestart: never

    stdout: ../../logs/attach.stdout
    stderr: ../../logs/attach.stderr